### ISSUE TITLE
 elph --workspace not saving permenantly on setup command

### ISSUE THREAD

**Issue by habiblawal1** [joe-chacko/elph#44]
When using the `elph --workspace <dir> setup` to change the workspace, the initial message shows the updated workspace, however if I press `elph setup` to check the config again, it will show my previous value for the Eclipse workspace instead of the new one. The image below shows the issue:
<img width="1720" alt="Screenshot 2023-10-16 at 15 07 50" src="https://github.com/joe-chacko/elph/assets/69252255/cbf2513b-5f2b-4160-af18-72161ca459d5">

**Comment by joe-chacko** [comment]
To change the workspace as it is now, you must use this syntax: `elph setup --workspace=<whatever>`
The ordering is important!
What you have found is the hidden option to override the workspace *for one invocation only*.
This is how we currently use picocli to implement the elph settings file.
If you have a suggestion for how to resolve this to avoid the confusion, I'm open to ideas.
Currently, the option you have used is hidden, undocumented, and not in the tab-completion.

**Comment by joe-chacko** [comment]
I suppose we could always overwrite the settings file whenever you invoke setup.
